name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # 监听 `main` 分支的推送操作

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: 检出代码
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: 设置 Node.js 环境
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16' # 或根据你的项目调整 Node.js 版本

    # Step 3: 安装依赖
    - name: Install dependencies
      run: npm install

    # Step 4: 构建项目
    - name: Build project
      run: gulp dist
      
    - name: Debug generated files
      run: |
        echo "Generated files in publish_dir:"
        ls -al ./dist

    # Step 5: 部署到 gh-pages 分支
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist  # 指定生成的静态文件目录
        force_orphan: true
